"""making changes

Revision ID: 9c88de06a2d7
Revises: 5ad9780eb08d
Create Date: 2022-12-05 14:50:49.435561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c88de06a2d7'
down_revision = '5ad9780eb08d'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('addres', sa.String(length=110), nullable=True))
    op.drop_column('user', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('user', 'addres')
    # ### end Alembic commands ###
