"""making changes

Revision ID: 5ad9780eb08d
Revises: b5f4cfb912c9
Create Date: 2022-12-05 14:49:14.602818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ad9780eb08d'
down_revision = 'b5f4cfb912c9'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
